### ISSUE TITLE
Direnv v2.32.0 supports GitHub Actions export

### ISSUE THREAD

**Issue by aabccd021** [HatsuneMiku3939/direnv-action#139]
For your information, since [v2.32.0](https://github.com/direnv/direnv/releases/tag/v2.32.0) direnv officially supports environment variable export for Github Actions.

Following steps are equivalent to this plugin's behavior:
```yaml
    - run: curl -sfL https://direnv.net/install.sh | bash

    - run: direnv allow

    - run: direnv export gha >> "$GITHUB_ENV"
```
