### ISSUE TITLE
Error: The process '/opt/hostedtoolcache/direnv/2.4.0/x64/direnv' failed with exit code 1

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [HatsuneMiku3939/direnv-action#240]
https://github.com/I-Want-ToBelieve/yakite/actions/runs/6976226486/job/18984517181

```yaml
name: Version

on:
  push:
    branches:
      - release/**

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Verify Nix Installation
        run: nix shell nixpkgs#nix-info -c nix-info -m

      - name: Install Direnv With Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
          nix_channel: nixpkgs

      - name: Export Direnv Env To Github Action
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.4.0

      - name: Install Dependencies
        run: pnpm install

      - name: Setup Git User
        run: git-user:setup

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



```
